# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=64)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('rule_version', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased by a worker'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=200)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('chain_depth', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'automation_job',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('in_app', 'In-app alert'), ('email', 'Email')], default='in_app', max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Shown to the recipient'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('cause', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'automation_notification',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField()),
                ('aggregate_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('chain_depth', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'automation_outbox_event',
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('template', models.CharField(choices=[('unassigned_lead', 'A01 unassigned lead'), ('missing_next_action', 'A02 opportunity without next action'), ('overdue_followup', 'A03 overdue follow-up'), ('stale_deal', 'A04 no activity in an open deal'), ('deal_won', 'A05 deal won'), ('milestone_overdue', 'A06 milestone overdue or blocked'), ('critical_ticket', 'A07 critical ticket created'), ('repeated_reschedule', 'A08 repeated rescheduling')], max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=False)),
                ('trigger', models.CharField(max_length=64)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('delay', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='', help_text='Why this rule exists, shown with every alert it raises.')),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_rule_definition',
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_version', models.PositiveIntegerField()),
                ('event_key', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=64)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_rule_execution',
            },
        ),
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(max_length=40, unique=True)),
                ('last_beat_at', models.DateTimeField()),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_scheduler_heartbeat',
            },
        ),
    ]
