# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='automation.outboxevent'),
        ),
        migrations.AddField(
            model_name='ruledefinition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruledefinition',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.ruledefinition'),
        ),
        migrations.AddField(
            model_name='job',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='automation.ruledefinition'),
        ),
        migrations.AddField(
            model_name='ruleexecution',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.outboxevent'),
        ),
        migrations.AddField(
            model_name='ruleexecution',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.ruledefinition'),
        ),
        migrations.AddField(
            model_name='ruleexecution',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='identity.workspace'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(condition=models.Q(('dispatched_at__isnull', True)), fields=['occurred_at'], name='idx_outbox_pending'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['workspace', 'aggregate_type', 'aggregate_id'], name='automation__workspa_c268fe_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['correlation_id'], name='automation__correla_44b5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ruledefinition',
            index=models.Index(fields=['workspace', 'trigger', 'enabled'], name='automation__workspa_a4a97c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruledefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'template', 'rule_version'), name='uniq_rule_template_version'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['workspace', 'recipient', 'state', '-created_at'], name='automation__workspa_864efa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['workspace', '-created_at'], name='automation__workspa_a600c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('workspace', 'dedupe_key'), name='uniq_unresolved_notification'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('state__in', ['pending', 'leased'])), fields=['due_at'], name='idx_job_runnable'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['workspace', 'state', 'due_at'], name='automation__workspa_cfe337_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'lease_expires_at'], name='automation__state_642a91_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('workspace', 'dedupe_key'), name='uniq_job_dedupe_key'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['workspace', '-executed_at'], name='automation__workspa_3b3be9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleexecution',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_key', 'rule_version', 'action_type'), name='uniq_rule_execution'),
        ),
    ]
