# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('received_at', models.DateField()),
                ('evidence_reference', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('adjustment_reason', models.TextField(blank=True, default='')),
                ('adjusts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='reporting.cashreceipt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='crm.client')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='crm.opportunity')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
            ],
            options={
                'db_table': 'reporting_cash_receipt',
                'indexes': [models.Index(fields=['workspace', 'received_at'], name='reporting_c_workspa_b0d6fd_idx'), models.Index(fields=['workspace', 'client', 'received_at'], name='reporting_c_workspa_f251bd_idx'), models.Index(fields=['workspace', 'currency', 'received_at'], name='reporting_c_workspa_40a63a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='ck_receipt_requires_currency'), models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='ck_receipt_requires_evidence'), models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('adjusts__isnull', False), _connector='OR'), name='ck_receipt_positive_unless_adjustment')],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_key', models.CharField(max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='identity.workspace')),
            ],
            options={
                'db_table': 'reporting_snapshot',
                'indexes': [models.Index(fields=['workspace', 'report_key', '-generated_at'], name='reporting_s_workspa_6b993b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('missed_deadline', 'Missed deadline'), ('repeated_reschedule', 'Repeated rescheduling'), ('neglected_lead', 'Lead with no owner or no contact'), ('no_next_action', 'Open deal with no next action'), ('handover_incomplete', 'Handover missing information'), ('delivery_blocked', 'Milestone blocked or overdue'), ('ticket_reopened', 'Ticket reopened after resolution')], max_length=32)),
                ('state', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('disputed', 'Disputed by the employee'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('employee_explanation', models.TextField(blank=True, default='')),
                ('employee_responded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_decision', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exceptions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='The person whose work this concerns, where there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
            ],
            options={
                'db_table': 'reporting_work_exception',
                'indexes': [models.Index(fields=['workspace', 'state', '-created_at'], name='reporting_w_workspa_39ba39_idx'), models.Index(fields=['workspace', 'subject', 'state'], name='reporting_w_workspa_b2993c_idx'), models.Index(fields=['workspace', 'kind', 'state'], name='reporting_w_workspa_cd47af_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['open', 'under_review', 'disputed'])), fields=('workspace', 'dedupe_key'), name='uniq_open_exception'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['resolved', 'dismissed']), _negated=True), models.Q(('review_decision', ''), _negated=True), _connector='OR'), name='ck_exception_closure_requires_decision')],
            },
        ),
    ]
