# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('template_key', models.CharField(blank=True, default='', max_length=64)),
                ('conversion_key', models.CharField(blank=True, default='', max_length=128)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.client')),
                ('originating_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
            ],
            options={
                'db_table': 'work_project',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('in_review', 'Submitted for review'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_note', models.TextField(blank=True, default='')),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('cancelled_reason', models.TextField(blank=True, default='')),
                ('cancellation_impact', models.TextField(blank=True, default='')),
                ('dependency_override_reason', models.TextField(blank=True, default='')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_milestones', to=settings.AUTH_USER_MODEL)),
                ('blocked_next_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dependency_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='work.project')),
            ],
            options={
                'db_table': 'work_milestone',
            },
        ),
        migrations.CreateModel(
            name='ScopeChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scope_change', 'Scope change'), ('defect', 'Defect')], max_length=16)),
                ('description', models.TextField()),
                ('commercial_impact', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_changes', to='work.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_changes', to='identity.workspace')),
            ],
            options={
                'db_table': 'work_scope_change',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('follow_up', 'Follow-up'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('admin', 'Administrative'), ('delivery', 'Delivery work')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('origin', models.CharField(choices=[('user', 'Created by a user'), ('rule', 'Created by an automation rule'), ('import', 'Created during import'), ('conversion', 'Created by deal conversion')], default='user', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('calendar_version', models.PositiveIntegerField(default=1)),
                ('original_due_at', models.DateTimeField()),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, default='')),
                ('stop_reason', models.TextField(blank=True, default='')),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('cancelled_reason', models.TextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
            ],
            options={
                'db_table': 'work_task',
            },
        ),
        migrations.CreateModel(
            name='TaskReschedule',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('previous_due_at', models.DateTimeField()),
                ('new_due_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='work.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reschedules', to='identity.workspace')),
            ],
            options={
                'db_table': 'work_task_reschedule',
            },
        ),
        migrations.CreateModel(
            name='MilestoneDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='work.milestone')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='work.milestone')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_dependencies', to='identity.workspace')),
            ],
            options={
                'db_table': 'work_milestone_dependency',
                'indexes': [models.Index(fields=['workspace', 'depends_on'], name='work_milest_workspa_fdf8f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('milestone', 'depends_on'), name='uniq_milestone_dependency'), models.CheckConstraint(condition=models.Q(('milestone', models.F('depends_on')), _negated=True), name='ck_milestone_no_self_dependency')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'client', 'status'], name='work_projec_workspa_317e54_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'owner', 'status'], name='work_projec_workspa_fea4d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('conversion_key__gt', '')), fields=('workspace', 'conversion_key'), name='uniq_project_conversion_key'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['workspace', 'project', 'sequence'], name='work_milest_workspa_862987_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['workspace', 'status', 'due_on'], name='work_milest_workspa_387f00_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['workspace', 'owner', 'status'], name='work_milest_workspa_c57d98_idx'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'in_review'), _negated=True), models.Q(('evidence', ''), _negated=True), _connector='OR'), name='ck_milestone_review_requires_evidence'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'blocked'), _negated=True), models.Q(('blocked_reason', ''), _negated=True), _connector='OR'), name='ck_milestone_blocked_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_reason', ''), _negated=True), _connector='OR'), name='ck_milestone_cancelled_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='scopechange',
            index=models.Index(fields=['workspace', 'project', 'kind'], name='work_scope__workspa_259ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'open')), fields=['workspace', 'owner', 'due_at'], name='idx_task_open_queue'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'due_at'], name='work_task_workspa_26ca88_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'opportunity', 'status'], name='work_task_workspa_e5f6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'owner', 'status'], name='work_task_workspa_9828b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('outcome', ''), _negated=True), models.Q(('stop_reason', ''), _negated=True), _connector='OR'), name='ck_task_completion_requires_outcome'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'blocked'), _negated=True), models.Q(('blocked_reason', ''), _negated=True), _connector='OR'), name='ck_task_blocked_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='taskreschedule',
            index=models.Index(fields=['workspace', 'task', 'changed_at'], name='work_task_r_workspa_18bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreschedule',
            index=models.Index(fields=['workspace', 'actor', 'changed_at'], name='work_task_r_workspa_4599bc_idx'),
        ),
    ]
