# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('linkedin', 'LinkedIn touch'), ('note', 'Note')], max_length=20)),
                ('outcome', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('evidence_type', models.CharField(choices=[('self_reported', 'Self-reported by the user'), ('provider_confirmed', 'Confirmed by a connected provider')], default='self_reported', max_length=24)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_activity',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('display_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending_handover', 'Pending handover'), ('accepted', 'Handover accepted'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending_handover', max_length=20)),
                ('accepted_scope', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='')),
                ('commercial_reference', models.CharField(blank=True, default='', max_length=500)),
                ('promised_start_on', models.DateField(blank=True, null=True)),
                ('promised_end_on', models.DateField(blank=True, null=True)),
                ('handover_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('handover_returned_at', models.DateTimeField(blank=True, null=True)),
                ('handover_returned_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('website', models.URLField(blank=True, default='')),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'crm_company',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('normalized_email', models.CharField(blank=True, default='', max_length=320)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('phone_e164', models.CharField(blank=True, default='', max_length=20)),
                ('job_title', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('outbound', 'Outbound prospecting'), ('event', 'Event'), ('import', 'Spreadsheet import'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('raw_import_values', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'crm_contact',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=128)),
                ('byte_size', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded, not yet previewed'), ('previewed', 'Previewed, awaiting confirmation'), ('committed', 'Commit accepted, queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('detected_headers', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('mapping_version', models.PositiveIntegerField(default=1)),
                ('default_country', models.CharField(blank=True, default='', max_length=2)),
                ('default_source', models.CharField(choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('outbound', 'Outbound prospecting'), ('event', 'Event'), ('import', 'Spreadsheet import'), ('other', 'Other'), ('unknown', 'Unknown')], default='import', max_length=32)),
                ('duplicate_policy', models.CharField(choices=[('skip', 'Skip duplicates'), ('update', 'Update existing')], default='skip', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_import_batch',
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('row_key', models.CharField(max_length=128)),
                ('raw_values', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('duplicate', 'Duplicate of an existing record'), ('invalid', 'Invalid'), ('skipped', 'Skipped by operator choice')], default='pending', max_length=16)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_import_row',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('outbound', 'Outbound prospecting'), ('event', 'Event'), ('import', 'Spreadsheet import'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacting', 'Contacting'), ('qualified', 'Qualified'), ('nurture', 'Nurture'), ('disqualified', 'Disqualified')], default='new', max_length=20)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('nurture_review_at', models.DateTimeField(blank=True, null=True)),
                ('disqualified_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('import_row_key', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('service', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='discovery', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('expected_close_on', models.DateField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('stage_entered_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('scope_reference', models.CharField(blank=True, default='', max_length=500)),
                ('commercial_reference', models.CharField(blank=True, default='', max_length=500)),
                ('accepted_scope_evidence', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_opportunity',
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, default='', max_length=20)),
                ('to_stage', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_stage_history',
            },
        ),
    ]
