# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('identity', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='crm.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='handover_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='default_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='crm.importbatch'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_rows', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='delivery_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_action_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_action_for', to='work.task'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='originating_opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_client', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='identity.workspace'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['workspace', 'normalized_name'], name='crm_company_workspa_7d5790_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'display_name'], name='crm_contact_workspa_752174_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'normalized_email'], name='crm_contact_workspa_b1d0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'phone_e164'], name='crm_contact_workspa_2f1ef7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('normalized_email__gt', '')), fields=('workspace', 'normalized_email'), name='uniq_contact_email_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('phone_e164__gt', '')), fields=('workspace', 'phone_e164'), name='uniq_contact_phone_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='crm_import__workspa_5b1252_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['file_expires_at'], name='crm_import__file_ex_93b68d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'owner', 'status'], name='crm_lead_workspa_e035ed_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='crm_lead_workspa_a12117_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('owner__isnull', True)), fields=['workspace', '-created_at'], name='idx_lead_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('import_row_key__gt', '')), fields=('workspace', 'import_row_key'), name='uniq_lead_import_row'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'state'], name='crm_import__batch_i_7a2083_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('workspace', 'row_key'), name='uniq_import_row_key'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_import_row_number'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['workspace', 'stage', '-created_at'], name='crm_opportu_workspa_a06dda_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['workspace', 'owner', 'stage'], name='crm_opportu_workspa_54f5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['workspace', 'next_action_at'], name='crm_opportu_workspa_b07f23_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['workspace', 'contact'], name='crm_opportu_workspa_55b49b_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('stage__in', ['discovery', 'proposal', 'qualified', 'negotiation'])), fields=['workspace', 'stage_entered_at'], name='idx_opportunity_open_age'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), models.Q(('currency', ''), _negated=True), _connector='OR'), name='ck_opportunity_amount_requires_currency'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'lost'), _negated=True), models.Q(('lost_reason', ''), _negated=True), _connector='OR'), name='ck_opportunity_lost_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'won'), _negated=True), models.Q(models.Q(('accepted_scope_evidence', ''), _negated=True), models.Q(('commercial_reference', ''), _negated=True)), _connector='OR'), name='ck_opportunity_won_requires_evidence'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'status'], name='crm_client_workspa_68aaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'delivery_owner', 'status'], name='crm_client_workspa_cdc547_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'pending_handover')), fields=['workspace', '-created_at'], name='idx_client_awaiting_handover'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', 'contact', '-occurred_at'], name='crm_activit_workspa_836a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', 'opportunity', '-occurred_at'], name='crm_activit_workspa_0064ac_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', 'author', '-occurred_at'], name='crm_activit_workspa_3ca4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', '-occurred_at'], name='crm_activit_workspa_d46570_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence_type', 'provider_confirmed'), _negated=True), models.Q(('provider_reference', ''), _negated=True), _connector='OR'), name='ck_activity_confirmed_requires_reference'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['workspace', 'opportunity', 'changed_at'], name='crm_stage_h_workspa_6fd8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['workspace', 'to_stage', 'changed_at'], name='crm_stage_h_workspa_92507d_idx'),
        ),
    ]
