# Generated by Django 5.2.17 on 2026-09-29 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('identity', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opportunity',
            name='idx_opportunity_open_age',
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('stage__in', ['discovery', 'negotiation', 'proposal', 'qualified'])), fields=['workspace', 'stage_entered_at'], name='idx_opportunity_open_age'),
        ),
    ]
