# Generated by Django 5.2.17 on 2026-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_stable_open_stage_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='need',
            field=models.TextField(blank=True, default=''),
        ),
    ]
