# Generated by Django 5.2.17 on 2026-10-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_need_and_fit'),
        ('work', '0002_task_milestone_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='follow_up_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.task'),
        ),
    ]
