# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('purpose', models.CharField(choices=[('summarise_notes', 'Summarise selected activity notes'), ('draft_follow_up', 'Draft a follow-up message')], max_length=32)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('input_versions', models.JSONField(blank=True, default=dict)),
                ('prompt_version', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=64)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('uncertainties', models.JSONField(blank=True, default=list)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('validation_error', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'ai_draft',
            },
        ),
        migrations.CreateModel(
            name='AIUsageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=32)),
                ('reserved_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estimated_input_tokens', models.PositiveIntegerField()),
                ('max_output_tokens', models.PositiveIntegerField()),
                ('actual_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('state', models.CharField(choices=[('reserved', 'Reserved, request in flight'), ('settled', 'Settled with actual usage'), ('released', 'Released without spend'), ('uncertain', 'Uncertain, awaiting reconciliation')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_note', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'ai_usage_reservation',
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('ceiling_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reserved_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('settled_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'ai_budget_period',
            },
        ),
    ]
