# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidraft',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='aiusagereservation',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiusagereservation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reservations', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='ai.aiusagereservation'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_budget_periods', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='aiusagereservation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ai.budgetperiod'),
        ),
        migrations.AddIndex(
            model_name='aidraft',
            index=models.Index(fields=['workspace', 'requested_by', '-created_at'], name='ai_draft_workspa_1816f1_idx'),
        ),
        migrations.AddIndex(
            model_name='aidraft',
            index=models.Index(fields=['workspace', 'purpose', '-created_at'], name='ai_draft_workspa_ca326e_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.UniqueConstraint(fields=('workspace', 'period_start'), name='uniq_ai_budget_period'),
        ),
        migrations.AddIndex(
            model_name='aiusagereservation',
            index=models.Index(fields=['workspace', 'state', '-created_at'], name='ai_usage_re_workspa_6387f2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagereservation',
            index=models.Index(fields=['period', 'state'], name='ai_usage_re_period__aa5013_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiusagereservation',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='uniq_ai_request_key'),
        ),
    ]
