# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
import django.utils.timezone
import modules.identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('time_zone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('calendar_version', models.PositiveIntegerField(default=1)),
                ('working_weekdays', models.JSONField(blank=True, default=list)),
                ('working_intervals', models.JSONField(blank=True, default=list)),
                ('holidays', models.JSONField(blank=True, default=list)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'identity_workspace',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'identity_user',
            },
            managers=[
                ('objects', modules.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='identity.workspace')),
            ],
            options={
                'db_table': 'identity_team',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'CEO and workspace owner'), ('sales_manager', 'Sales manager'), ('sales_rep', 'Sales representative'), ('delivery_manager', 'Delivery manager'), ('delivery_employee', 'Delivery employee'), ('admin', 'Workspace administrator'), ('client', 'Client user (Release 3)')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('invited', 'Invited, not yet accepted')], default='invited', max_length=16)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_reason', models.TextField(blank=True, default='')),
                ('mfa_enrolled', models.BooleanField(default=False)),
                ('is_available_for_assignment', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='identity.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='identity.workspace')),
            ],
            options={
                'db_table': 'identity_membership',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'CEO and workspace owner'), ('sales_manager', 'Sales manager'), ('sales_rep', 'Sales representative'), ('delivery_manager', 'Delivery manager'), ('delivery_employee', 'Delivery employee'), ('admin', 'Workspace administrator'), ('client', 'Client user (Release 3)')], max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='identity.workspace')),
            ],
            options={
                'db_table': 'identity_invitation',
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_team_name'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'status'], name='identity_me_workspa_052622_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'role'], name='identity_me_workspa_24ab1d_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='identity_me_user_id_b450f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_membership_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['workspace', 'email'], name='identity_in_workspa_866710_idx'),
        ),
    ]
