# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, default='', max_length=320)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'State transition'), ('login', 'Login'), ('login_failed', 'Failed login'), ('permission_denied', 'Permission denied'), ('export', 'Export'), ('import', 'Import'), ('rule_action', 'Automated rule action'), ('correction', 'Correction')], max_length=32)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'common_audit_event',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common_idempotency_record',
            },
        ),
    ]
