# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('identity', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('origin', models.CharField(choices=[('client_request', 'Client request'), ('internal_issue', 'Internal issue')], default='client_request', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('state', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('waiting_customer', 'Waiting on the customer'), ('waiting_internal', 'Waiting on us'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('waiting_reason', models.TextField(blank=True, default='')),
                ('waiting_review_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=300)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('closure_test_result', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.client')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='work.milestone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tickets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='work.project')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('waiting_next_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='identity.workspace')),
            ],
            options={
                'db_table': 'support_ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal only'), ('client_visible', 'Visible to the client')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='support.ticketcomment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='identity.workspace')),
            ],
            options={
                'db_table': 'support_ticket_comment',
            },
        ),
        migrations.CreateModel(
            name='TicketStateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('superseded_resolution', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='support.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_state_history', to='identity.workspace')),
            ],
            options={
                'db_table': 'support_ticket_state_history',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'state', 'priority'], name='support_tic_workspa_843cad_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'owner', 'state'], name='support_tic_workspa_b1785d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workspace', 'client', 'state'], name='support_tic_workspa_a594be_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('state__in', ['waiting_customer', 'waiting_internal'])), fields=['workspace', 'waiting_review_at'], name='idx_ticket_waiting_review'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'resolved'), _negated=True), models.Q(models.Q(('resolution_note', ''), _negated=True), models.Q(('closure_test_result', ''), _negated=True)), _connector='OR'), name='ck_ticket_resolution_requires_evidence'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['waiting_customer', 'waiting_internal']), _negated=True), models.Q(('waiting_reason', ''), _negated=True), _connector='OR'), name='ck_ticket_waiting_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['workspace', 'ticket', 'created_at'], name='support_tic_workspa_e1450c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['workspace', 'visibility'], name='support_tic_workspa_011c47_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatehistory',
            index=models.Index(fields=['workspace', 'ticket', 'changed_at'], name='support_tic_workspa_815c00_idx'),
        ),
    ]
